# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Pieter Belmans"
email: pbelmans@math.uni-bonn.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pbelmans.ncag.info" # the base hostname & protocol for your site

permalink: /blog/:year/:month/:day/:title/

paginate: 5
paginate_path: "/archive/:num/"
gems:
  - jekyll-paginate
  - jekyll-redirect-from
